/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.rpc.LinkedList;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
