/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
import com.google.protobuf.gradle.*

plugins {
    id("buildlogic.java-library-conventions")

    // https://github.com/google/protobuf-gradle-plugin/tree/master
    id("com.google.protobuf") version "0.9.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
    implementation("com.google.protobuf:protobuf-java:4.30.2")
    // https://mvnrepository.com/artifact/io.grpc/grpc-all
    implementation("io.grpc:grpc-stub:1.71.0")
    implementation("io.grpc:grpc-protobuf:1.71.0")
    // The generated GRPC code needs this
    implementation("javax.annotation:javax.annotation-api:1.3.2")

    protobuf(files("protobufs/"))
}

sourceSets {
    main {
        java {
            srcDirs("build/generated/source/proto/main/grpc")
            srcDirs("build/generated/source/proto/main/java")
        }
        proto {
            srcDir("../../idl/")
        }
    }
}

protobuf {
    protoc {
        // https://mvnrepository.com/artifact/com.google.protobuf/protoc
        artifact = "com.google.protobuf:protoc:4.30.2"
    }

    plugins {
        id("grpc") {
            // https://mvnrepository.com/artifact/io.grpc/protoc-gen-grpc-java
            artifact = "io.grpc:protoc-gen-grpc-java:1.71.0"
        }
    }

    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("grpc") { }
            }
        }
    }
}